### ISSUE TITLE
Demo server and client not compatible with PHP 5.6

### ISSUE THREAD

**Issue by pfrenssen** [openeuropa/pcas#6]
Both the `demo-server` and `demo-client` applications are using PHP7-specific functionality so they are not compatible with the PHP5.6 target which is specified in the Composer manifest.

More specifically, they are using the null coalescing operator `??` in the `bin/console` launchers. This is a feature that was added in PHP 7.0. 

Ref. [Null coalescing operator](http://php.net/manual/en/migration70.new-features.php#migration70.new-features.null-coalesce-op)

**Comment by ademarco** [comment]
Good point, we should have all our libraries compatible with PHP 5.6, \cc @drupol.

**Comment by ademarco** [comment]
Yes, unfortunately for libraries we are stuck with PHP 5.6 because they might be used on Drupal 7 platfrom too. While for Drupal 8 modules we can safely be on PHP 7.1

**Comment by drupol** [comment]
Oh nose...

**Comment by ademarco** [comment]
Demo client and server have been moved out from pCAS to their own repo here: https://github.com/openeuropa/pcas-demo fixing this issue in the process, closing.
