### ISSUE TITLE
Decouple the user object from Symfony

### ISSUE THREAD

**Issue by pfrenssen** [openeuropa/pcas#8]
The `PCasUser` object is adhering to Symfony's `UserInterface` specification. This makes it less flexible to use in other PHP frameworks, especially since this interface defines a number of methods which doesn't make sense in the scope of CAS authentication, such as `::getPassword()` and `::getSalt()`.

I think it would be a good idea to create a Symfony-specific component which has this library as a dependency and wraps the PCas-classes inside versions that comply with Symfony. The classes `PCasGuardAuthenticator` and `PCasUserProvider` also seem to have little use outside of Symfony.

**Comment by drupol** [comment]
Thanks, this is now fixed.
